name: Node.js CI

on:
  - push
  - pull_request

env:
  DENO_INSTALL: /usr/local

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init MySQL
        run: sudo /etc/init.d/mysql start

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Deno
        run: curl -fsSL https://deno.land/install.sh | sh

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run test
        run: npm test
        env:
          MYUSER: root
          MYPASS: root

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
